version: '3.8'

services:
  base-java-image:
    build:
      context: .
    image: ghcr.io/concepting-com-br/base-java-image:${BUILD_VERSION}
    container_name: base-java-image
    hostname: base-java-image
    depends_on:
      - etcd
      
  etcd:
    image: ghcr.io/concepting-com-br/etcd:1.0.0
    container_name: etcd
    hostname: etcd
    ports: 
      - 2379:2379
    volumes:
      - ./etc/settings.json:/home/user/etc/app.json
      - etcd-data:/home/user/data

volumes:
  etcd-data:
  